### PR TITLE
Remove cast to AnyObject and use Any instead

### PR DESCRIPTION
**Pull request by jgrandelli**

### CODE REVIEW

**Comment by codecaffeine** [comment]
Alright, I had to read [SE-0116](https://github.com/apple/swift-evolution/blob/master/proposals/0116-id-as-any.md) and the [mailing list thread](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160627/023203.html) to really understand this change in Swift 3.

Previously `id` was imported as `AnyObject` and there were exceptions made to bridge between certain value types (String, Dictionary, Array) and their corresponding reference type (NSString, NSDictionary, NSArray).

[SE-0072](https://github.com/apple/swift-evolution/blob/master/proposals/0072-eliminate-implicit-bridging-conversions.md) eliminated this implicit bridging but lead to a some issues:
1. A lot of the frameworks depend on `id`
2. Swift 3 introduces a lot of new value types (URL, Data, Date)

This made a whole lot of explicit bridging necessary which made working with the framework a lot harder. Because of this, Apple decided to import `id` as `Any` instead of `AnyObject` and add some custom rules:

> 1. We change the behavior of Objective-C APIs imported into Swift so that the `id` type is imported as `Any` in bridgeable positions. At compile time and runtime, the compiler introduces a **universal bridging conversion** operation when a Swift value or object is passed into Objective-C as an id parameter.
> 2. When `id` values are brought into Swift as `Any`, we use the runtime's existing **ambivalent dynamic casting** support to handle bridging back to either class references or Swift value types.

So… this change looks looks good.

**Comment by jgrandelli** [comment]
I went a little deeper. Looking at the work that was done in the base branch, the cast is only neccessary because we are casting to a `Date`. If we keep `NSDate` no additional cast necessary. So i'm not really that concerned with _which_ method we keep (cast to `NSDate` and keep `AnyObject` or cast to `Date` and go with `Any`). And thanks for the additional doc references @codecaffeine

**Comment by codecaffeine** [comment]
It might be prudent to follow Apple’s lead here and cast as `Any` so we can decide to use the value type `Date` if we want to.

**Comment by jgrandelli** [comment]
Sounds good to me, if you're cool with this, go ahead and merge it

**Pull request merged**
